[2025-06-08T22:44:20.021+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-06-08T22:44:17.261953+00:00 [queued]>
[2025-06-08T22:44:20.026+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-06-08T22:44:17.261953+00:00 [queued]>
[2025-06-08T22:44:20.026+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-06-08T22:44:20.033+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-06-08 22:44:17.261953+00:00
[2025-06-08T22:44:20.041+0000] {standard_task_runner.py:57} INFO - Started process 192 to run task
[2025-06-08T22:44:20.053+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2025-06-08T22:44:17.261953+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpg_t1gpl8']
[2025-06-08T22:44:20.059+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask stream_data_from_api
[2025-06-08T22:44:20.202+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2025-06-08T22:44:17.261953+00:00 [running]> on host 537e30a201fe
[2025-06-08T22:44:20.811+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T22:44:17.261953+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T22:44:17.261953+00:00'
[2025-06-08T22:44:21.328+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.4', 29092)]>: connecting to broker:29092 [('10.89.0.4', 29092) IPv4]
[2025-06-08T22:44:21.351+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <checking_api_versions_recv> [IPv4 ('10.89.0.4', 29092)]>: Broker version identified as 2.6
[2025-06-08T22:44:21.351+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('10.89.0.4', 29092)]>: Connection complete.
[2025-06-08T22:44:21.823+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connecting> [IPv4 ('10.89.0.4', 29092)]>: connecting to broker:29092 [('10.89.0.4', 29092) IPv4]
[2025-06-08T22:44:21.825+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('10.89.0.4', 29092)]>: Connection complete.
[2025-06-08T22:44:21.826+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('10.89.0.4', 29092)]>: Closing connection. 
[2025-06-08T22:44:21.950+0000] {cluster.py:313} WARNING - Topic users_created is not available during auto-create initialization
[2025-06-08T22:44:22.136+0000] {cluster.py:313} WARNING - Topic users_created is not available during auto-create initialization
[2025-06-08T22:44:22.295+0000] {cluster.py:313} WARNING - Topic users_created is not available during auto-create initialization
[2025-06-08T22:44:44.510+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:44:45.943+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:44:46.978+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:44:48.405+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:44:49.528+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:44:50.981+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:44:52.437+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:44:53.943+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:44:55.883+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:44:56.982+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:44:58.441+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:45:00.490+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:45:03.456+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:45:05.502+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:45:07.943+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:45:09.954+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:45:11.438+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:45:12.980+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:45:14.850+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:45:16.372+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:45:17.404+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:45:19.027+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:45:20.467+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-08T22:45:21.635+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('10.89.0.4', 29092)]>: Closing connection. 
[2025-06-08T22:45:21.639+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-06-08T22:45:21.679+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20250608T224417, start_date=20250608T224420, end_date=20250608T224521
[2025-06-08T22:45:21.736+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-06-08T22:45:21.768+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
