[2025-06-09T00:00:02.618+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-06-08T00:00:00+00:00 [queued]>
[2025-06-09T00:00:02.629+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-06-08T00:00:00+00:00 [queued]>
[2025-06-09T00:00:02.629+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-06-09T00:00:02.641+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-06-08 00:00:00+00:00
[2025-06-09T00:00:02.667+0000] {standard_task_runner.py:57} INFO - Started process 795 to run task
[2025-06-09T00:00:02.670+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'scheduled__2025-06-08T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpldje9z8m']
[2025-06-09T00:00:02.680+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask stream_data_from_api
[2025-06-09T00:00:02.890+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api scheduled__2025-06-08T00:00:00+00:00 [running]> on host 537e30a201fe
[2025-06-09T00:00:03.823+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T00:00:00+00:00'
[2025-06-09T00:00:04.062+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.4', 29092)]>: connecting to broker:29092 [('10.89.0.4', 29092) IPv4]
[2025-06-09T00:00:04.097+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <checking_api_versions_recv> [IPv4 ('10.89.0.4', 29092)]>: Broker version identified as 2.6
[2025-06-09T00:00:04.098+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('10.89.0.4', 29092)]>: Connection complete.
[2025-06-09T00:00:04.937+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connecting> [IPv4 ('10.89.0.4', 29092)]>: connecting to broker:29092 [('10.89.0.4', 29092) IPv4]
[2025-06-09T00:00:04.942+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('10.89.0.4', 29092)]>: Connection complete.
[2025-06-09T00:00:04.942+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('10.89.0.4', 29092)]>: Closing connection. 
[2025-06-09T00:00:41.124+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-09T00:00:42.655+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-09T00:00:44.260+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-09T00:00:46.737+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-09T00:00:50.199+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-09T00:00:52.041+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-09T00:00:53.172+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-09T00:00:55.176+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-09T00:00:56.687+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-09T00:00:58.648+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-09T00:00:59.668+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-09T00:01:01.677+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-09T00:01:03.159+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-09T00:01:04.264+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('10.89.0.4', 29092)]>: Closing connection. 
[2025-06-09T00:01:04.269+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-06-09T00:01:04.323+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20250608T000000, start_date=20250609T000002, end_date=20250609T000104
[2025-06-09T00:01:04.412+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-06-09T00:01:04.448+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
