[2025-06-16T09:48:48.905+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-06-16T09:48:47.015609+00:00 [queued]>
[2025-06-16T09:48:48.912+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-06-16T09:48:47.015609+00:00 [queued]>
[2025-06-16T09:48:48.912+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-06-16T09:48:48.920+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-06-16 09:48:47.015609+00:00
[2025-06-16T09:48:48.938+0000] {standard_task_runner.py:57} INFO - Started process 168 to run task
[2025-06-16T09:48:48.942+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2025-06-16T09:48:47.015609+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpyu56i7vl']
[2025-06-16T09:48:48.945+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask stream_data_from_api
[2025-06-16T09:48:48.999+0000] {task_command.py:410} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2025-06-16T09:48:47.015609+00:00 [running]> on host b8c7bf911999
[2025-06-16T09:48:49.385+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T09:48:47.015609+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-16T09:48:47.015609+00:00'
[2025-06-16T09:48:49.877+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('10.89.0.6', 29092)]>: connecting to broker:29092 [('10.89.0.6', 29092) IPv4]
[2025-06-16T09:48:49.893+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <checking_api_versions_recv> [IPv4 ('10.89.0.6', 29092)]>: Broker version identified as 2.6
[2025-06-16T09:48:49.893+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('10.89.0.6', 29092)]>: Connection complete.
[2025-06-16T09:48:50.490+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connecting> [IPv4 ('10.89.0.6', 29092)]>: connecting to broker:29092 [('10.89.0.6', 29092) IPv4]
[2025-06-16T09:48:50.492+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('10.89.0.6', 29092)]>: Connection complete.
[2025-06-16T09:48:50.492+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('10.89.0.6', 29092)]>: Closing connection. 
[2025-06-16T09:48:50.591+0000] {cluster.py:313} WARNING - Topic users_created is not available during auto-create initialization
[2025-06-16T09:49:34.507+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-16T09:49:37.538+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-16T09:49:44.953+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-16T09:49:46.933+0000] {kafka_stream.py:56} ERROR - an error occurred: list index out of range
[2025-06-16T09:49:50.135+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('10.89.0.6', 29092)]>: Closing connection. 
[2025-06-16T09:49:50.168+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-06-16T09:49:50.455+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20250616T094847, start_date=20250616T094848, end_date=20250616T094950
[2025-06-16T09:49:50.724+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-06-16T09:49:50.867+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
